### ISSUE TITLE
AIDotNet 是否打算和 SciSharp社区联动互补啊.

### ISSUE THREAD

**Issue by sgf** [AIDotNet/mem0.NET#1]
因为python是深度学习的主流.
感觉C#在机器学习这块严重落后python.

但是SciSharp(社区)结合
TorchSharp(MS项目) 之类的.
大有可为.
如果能够逐渐形成规模,产生积累,优势互补的话或许可以把生态补足.

**Comment by 239573049** [comment]
我们于SciSharp社区并没有相互认识的人，大佬如果有交流的群可以一块交流

**Comment by sgf** [comment]
我也不认识,不过开源社区没有隔阂.我的意思是,SciSharp社区不知是不是国人组件的,但是里面有国人开发的项目.
我的意思是,AIDotnet 社区后面有些轮子可以不用重复做.这样到时候两个社区优势互补,强强联合,到时候可以组合成完整的深度学习开发工具链.
